version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    restart: always
    container_name: my_postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5434:5432"  # esposto sul host
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  api:
    build:
      context: ./backend
      dockerfile: dockerfile
    container_name: my_backend
    depends_on:
      - postgres
    environment:
      DB_PASSWORD: mypassword
      DB_NAME: mydb
    ports:
      - "3000:3000"
    # se vuoi montare il codice per sviluppo:
    # volumes:
    #  - .:/app

volumes:
  postgres_data:
  pgadmin_data:
